# Generated by Django 3.2.16 on 2023-01-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_follow_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_text_author',
        ),
    ]
